export enum ActionTypes {
  registerSuccess,
  registerFail,
  userLoaded,
  authError,
  userLoginSuccess,
  userLoginFail,
  fetchAccounts,
  postNewAccount,
  fetchMeetings,
  postNewMeeting,
  fetchRoutes,
  postNewRoute,
  fetchTrucks,
  postNewTruck,
  fetchWorkOrders,
  postNewWorkOrder,
}
